# Exported from Render on 2025-07-08T08:24:22Z
services:
- type: web
  name: DENTO-backend
  runtime: elixir
  repo: https://github.com/akashdahiya2/DENTO-backend
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  autoDeployTrigger: commit
version: "1"
